version: '3'

services:

  proxy:
    container_name: local_proxy
    image: local_proxy
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    expose:
      - 666
      - 8888
    networks:
      local_proxy:
        ipv4_address: 172.28.0.2

networks:
  local_proxy:
    name: local_proxy
    ipam:
      config:
        - subnet: 172.28.0.0/24
